name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run Jekyll
      run: bundle exec jekyll build
      
    - name: Upload file to bucket
      uses: koraykoska/s3-upload-github-action@master
      env:
        FILE: _site
        S3_ENDPOINT: 'cellar-c2.services.clever-cloud.com'
        S3_BUCKET: test-clevercloud-static-hosting.for.vertx.project
        S3_ACCESS_KEY_ID: ${{ secrets.KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.KEY_SECRET }}
